### ISSUE TITLE
webview detection

### ISSUE THREAD

**Issue by jney** [mileusna/useragent#12]
Hi @mileusna, is there a way to detect if it's a webview or a browser? thank you

**Comment by jney** [comment]
with some (few) search, it looks like it can be detected with `X-Requested-With` header. Please close the ticket if you confirm this approach

**Comment by jney** [comment]
another approach would be to detect:

```js
   // if it says it's a webview, let's go with that
  'WebView',
  // iOS webview will be the same as safari but missing "Safari"
  '(iPhone|iPod|iPad)(?!.*Safari)',
  // Android Lollipop and Above: webview will be the same as native but it will contain "wv"
  // Android KitKat to lollipop webview will put {version}.0.0.0
  'Android.*(wv|.0.0.0)',
  // old chrome android webview agent
  'Linux; U; Android'
```

check [here](https://github.com/atomantic/is-ua-webview/blob/master/data/rules.js)

**Comment by mileusna** [comment]
No user agent string provided.

**Comment by mileusna** [comment]
No user agent string provided.
