### ISSUE TITLE
Application User Agent detection

### ISSUE THREAD

**Issue by craumix** [mileusna/useragent#21]
I'm not quite sure where this fits in, but currently [Seafiles](https://www.seafile.com/en/home/`) UA is classified as desktop, which in some cases leads to really skewed metrics for me.  
Is there a policy regarding such application user agents, should they be considered bots? Or is classifying them as desktop/mobile intended behaviour?

**Comment by mileusna** [comment]
What is it? Bot? Can you give me exact User-Agent string, I can't find any UA which contains "Seafile" in my rich user agents database?

**Comment by craumix** [comment]
The UA string is `Seafile/9.0.2 (Linux)`. 
Normally it shouldn't connect to the site, but sometimes it seems to do so, causing a fair amount of garbage in the metrics.

I understand that it's not exactly a bot, but I still wonder if the current classification is intentional. If it is, I will fix my case locally.

**Comment by mileusna** [comment]
What it does? Download file? Is it initiated by the user or by the server?

This type of unconventional tools usually have all flags set to false, but this one declares "Linux" in user agent string, which set Desktop to true.

**Comment by craumix** [comment]
The Client mostly periodically polles the server, or syncs files in the background.
