### ISSUE TITLE
bytedance bot is not cannot be identified

### ISSUE THREAD

**Issue by maczam** [mileusna/useragent#26]
User Agent :  Mozilla/5.0 (compatible; Bytespider; spider-feedback@bytedance.com) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.0.0 Safari/537.36
Version : v1.3.4

String | Mozilla/5.0 (compatible; Bytespider; spider-feedback@bytedance.com) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.0.0 Safari/537.36
-- | --
Name | Chrome
Version | 70.0.0.0
OS |  
OSVersion |  
Device |  
Mobile | false
Tablet | false
Desktop | false
Bot | false

using online web  test: [https://ip360.me/ua/?ua=Mozilla/5.0%20(compatible;%20Bytespider;%20spider-feedback@bytedance.com)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/70.0.0.0%20Safari/537.36](url)

**Comment by mileusna** [comment]
Is this the bot TikTok use for fetching content?
