### ISSUE TITLE
Add Samsung Browser to be recognised as Android device

### ISSUE THREAD

**Issue by justlx** [mileusna/useragent#29]
I have an issue with detecting mobile devices using isAndroid because SamsungBrowser is not recognised as mobile device:
```go
package main

import (
	"fmt"

	useragentent "github.com/mileusna/useragent"
)

func main() {
	ua := useragentent.Parse("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/22.0 Chrome/111.0.5563.116 Safari/537.36")
	fmt.Println(ua.IsAndroid())
}

```

This one gives me false and expected one would be true.

Device information:
```
Galaxy Tab A8
Model number: SM-X200
```

**Comment by mileusna** [comment]
Thank you, I will check. Package does recognize SamsungBrowser, but they usually also have "Android" keyword in the user agent.
