### ISSUE TITLE
Command line version

### ISSUE THREAD

**Issue by ychaouche** [mileusna/useragent#44]
Hello there,
is there a command line version of this tool?
would be most useful to parse and summarize web server logs.

**Comment by mileusna** [comment]
This is a package and you can use it to make CLI log analyzer but it is out of the scope of this package to make end user programs.

**Comment by ychaouche** [comment]
thanks @mileusna.  
Just in case someone else lands here through a web search or by following a link,  
here's an attempt at writing a command line tool that uses this package to parse ua strings from web server logs.  
It has been generated by copilot and slightly edited:

```
package main

import (
    "fmt"
    "os"
    "github.com/mileusna/useragent"
)



func main() {
    if len(os.Args) < 2 {
        fmt.Println("Usage: ua_summary '<User-Agent string>'")
        return
    }

    uaString := os.Args[1]
    ua := useragent.Parse(uaString)

// we need to use a function here that returns "-" if string is empty

    fmt.Printf("%s %s / %s %s / %s", ua.Name, ua.Version, ua.OS, ua.OSVersion, ua.Device)
    if ua.Mobile {
        fmt.Println("(Mobile)")
    } else if ua.Tablet {
        fmt.Println("(Tablet)")
    } else if ua.Desktop {
        fmt.Println("(Desktop)")
    } else if ua.Bot {
        fmt.Println("(Bot)")
    }

}

```
