### ISSUE TITLE
safari desktop considered as mobile

### ISSUE THREAD

**Issue by jney** [mileusna/useragent#5]
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15" is considered as mobile, but it is desktop

**Comment by jney** [comment]
My bad. It looks it actually works

**Comment by mfarkan** [comment]
Hello, I'm trying to get the Device name user-agent just like above and the device name is empty, Is there any chance to upgrade lib to fix this user-agent?

e.g  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
