### ISSUE TITLE
mobiele user being detected as Desktop

### ISSUE THREAD

**Issue by guilhermebotossi** [mileusna/useragent#8]
I tried with the following user-agent, and it detected as desktop:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/79.0.3945.147 Safari/534.24 XiaoMi/MiuiBrowser/12.11.5-gn`

If possible, I'll try to make the changes this weekend and send a PR, if not, I'm just registering this User-agent for future improvement.

Thanks a lot

**Comment by mileusna** [comment]
How this UA should be registered? Mobile and browser MiuiBrowser?
